repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: .venv/bin/ruff format
        language: system
        types: [python]
        pass_filenames: false
        args: [src, tests]
        
      - id: ruff-check
        name: ruff check
        entry: .venv/bin/ruff check --fix
        language: system
        types: [python]
        pass_filenames: false
        args: [src, tests]
        
      - id: pytest
        name: pytest
        entry: bash -c 'if [ -d "tests" ] && [ "$(ls -A tests)" ]; then .venv/bin/pytest tests; else echo "No tests found. Skipping tests."; exit 0; fi'
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
